name: Telugu Animation Pipeline

on:
  #schedule:
  #  - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows manual triggering

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  # Job 1: Fetch and Generate Script
  fetch_and_generate_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch Trending Topics and Generate Script
        run: python scripts/fetch_and_generate.py

  # Job 2: Generate Speech from text
  text_to_speech:
    runs-on: ubuntu-latest
    needs: fetch_and_generate_script
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Convert Script to Voice
        run: python scripts/generate_voice.py

  # Job 3: Animate Video using Blender
  animate_video:
    runs-on: ubuntu-latest
    needs: text_to_speech
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Blender
        run: sudo apt-get install -y blender

      - name: Render Animation
        run: blender -b assets/animation_template.blend -P scripts/render_animation.py

  # Job 4: Merge Animation and Voiceover
  merge_audio_video:
    runs-on: ubuntu-latest
    needs: animate_video
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
  
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
  
      - name: Merge Animation and Voiceover
        run: python merge_audio_video.py

  #upload_to_youtube:
  #  runs-on: ubuntu-latest
  #  needs: merge_audio_video
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v2
  #
  #    - name: Install YouTube API Dependencies
  #      run: pip install -r requirements.txt
  #
  #    - name: Upload to YouTube
  #      run: python scripts/upload_video.py
