name: Telugu Animation Pipeline

on:
  push:
  #schedule:
  #  - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows manual triggering

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  # Complete Animation Pipeline in One Job
  animation_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch Trending Topics and Generate Script
        run: python scripts/fetch_and_generate.py  # This will generate the script file

      - name: Convert Script to Voice
        run: python scripts/generate_voice.py  # This will convert the generated script to voice (audio)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: output/

      - name: Install Blender
        run: |
            sudo apt-get install -y blender  # Install Blender for animation rendering
            blender -version  # Check Blender version

      #- name: Render Animation
      #  run: |
      #    blender -b assets/animation_template.blend -P scripts/render_animation.py  # Run Blender animation
#
      #- name: Merge Animation and Voiceover
      #  run: python merge_audio_video.py  # Merge the animation and audio into a final video
